micronaut:
  application:
    name: demo
  server:
    port: 8081
hello:
  controller:
    path: "/hello"
  service:
    greeting: "Hello from service"
  config:
    greeting:
      en: "Hello"
      de: "Hallo"
